# Example configuration file for updating the W-Q dataset.

token: "yWeTFbARG6kWX9X4N804hA"  # see https://webknossos.org/auth/token Auth Token
revision_path: "WQ"
scale: [5.0, 5.0, 50.0]
segmentation_layer: "segmentations"
image_layer: "images"
online_dataset: "W-Q_x0_y0_z0_2022-01-02_00-43-18"
online_team: "4fd6473e68256c0a"  # see https://webknossos.org/auth/token Organization ID
annotation_url: "https://webknossos.org/annotations/Explorational/61d5c797010000b500b3a085"

